version: '3'
services:
  redis:
    image: redis
    command: redis-server --maxmemory 100mb --maxmemory-policy allkeys-lru

  reset:
    build: .
    command: python reset_tasks.py
    depends_on:
      - redis
    volumes:
      - .:/app

  web:
    build: .
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - reset
    volumes:
      - .:/app

  worker:
    build: .
    command: celery -A celery_worker worker --loglevel=info --concurrency=4
    depends_on:
      - redis
      - reset
    volumes:
      - .:/app