version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  web:
    build: .
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - .:/app

  worker:
    build: .
    command: celery -A celery_worker worker --loglevel=info --concurrency=8
    depends_on:
      - redis
    volumes:
      - .:/app
